---
- name: Copy iscsid.conf
  template:
    src: iscsid.conf.j2
    dest: /etc/iscsi/iscsid.conf
    backup: yes

- name: Copy initiatorname.iscsi
  template:
    src: initiatorname.iscsi.j2
    dest: /etc/iscsi/initiatorname.iscsi
    backup: yes
  register: iscsi_register_initiatorname
  
- name: Restart iSCSI service if initial configuration changed
  service:
    name:  'open-iscsi'
    state: 'restarted'
  when: iscsi_register_initiatorname|d() and iscsi_register_initiatorname.changed

- name: Copy multipath.conf
  template:
    src: multipath.conf.j2
    dest: /etc/multipath.conf
  notify:
    - restart multipath-tools

- name: Enable multipathd
  modprobe:
    name: dm-multipath
    state: present
    

