---
- name: Calico | Install calicoctl bin
  copy:
     src={{ local_release_dir }}/calico/bin/calicoctl
     dest={{ bin_dir }}
     mode=0755
  notify: restart calico-node

- name: Calico | Create calicoctl symlink (needed by kubelet)
  file: src=/usr/local/bin/calicoctl dest=/usr/bin/calicoctl state=link

- name: Calico | Configure calico-node desired pool
  shell: calicoctl pool add {{ kube_pods_subnet }}
  environment:
     ETCD_AUTHORITY: "{{ groups['etcd'][0] }}:2379"
  run_once: true
  delegate_to: "{{ groups['etcd'][0] }}"

- name: Calico | Write calico-node systemd init file
  template: src=calico/calico-node.service.j2 dest=/etc/systemd/system/calico-node.service
  register: newservice
  notify:
    - reload systemd
    - restart calico-node

- name: Calico | daemon-reload
  command: systemctl daemon-reload
  when: newservice|changed
  changed_when: False

- name: Calico | Enable calico-node
  service: name=calico-node enabled=yes state=started

- name: Calico | Disable node mesh
  shell: calicoctl bgp node-mesh off
  when: peer_with_router|default(false) and inventory_hostname in groups['kube-node']

- name: Calico | Configure peering with router(s)
  shell: calicoctl node bgp peer add {{ item.router_id }} as {{ item.as }}
  with_items: peers
  when: peer_with_router|default(false) and inventory_hostname in groups['kube-node']

- name: Calico | Install netfilter-persistent
  apt:
    name: netfilter-persistent
    state: present

- name: Calico | Install iptables-persistent
  apt:
    name: iptables-persistent
    state: present

- name: Calico | Copy iptables template rules over to /etc/iptables
  template: src=calico/iptables.v4.j2 dest=/etc/iptables/rules.v4
  notify: restart netfilter-persistent

- name: Calico | Delete ipv6 rules
  template: src=calico/iptables.v6.j2 dest=/etc/iptables/rules.v6
  notify: restart netfilter-persistent
